<template>
  <fields
    :fields="flow.fields"
    :entries="entries"
    :before-upload-func="beforeUploadFunc"
    :file-params="fileParams"
  />
</template>

<script>
import Fields from '../../src/components/field/index.vue'

export default {
  components: {
    Fields,
  },

  data() {
    return {
      flow: {},
      fileParams: {},
      entries: [
        {
          id: 4889239,
          field_id: 10741,
          option_id: null,
          value: '成都短发',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4889238,
          field_id: 10725,
          option_id: null,
          value: '2021-02-10',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4889237,
          field_id: 10171,
          option_id: null,
          value: '510824199707244910',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4889236,
          field_id: 10172,
          option_id: null,
          value: '15287162323',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4909978,
          field_id: 10785,
          option_id: null,
          value: '下载.jpeg',
          choice_id: null,
          value_id: 948501,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
          attachment: {
            id: 948501,
            name: '下载.jpeg',
            size: '4027',
            mime_type: 'image/jpeg',
            extension: 'image',
            extra_info: {},
            download_url:
              'http://gxattachment.skylarkly.com/1/create_responses/6-1610522321-6af17a840a157661ac83ddd06ef6f339-Wed Jan 13 2021 15:18:38 GMT+0800 (中国标准时间)?attname=%E4%B8%8B%E8%BD%BD.jpeg&e=1610527775&token=fy5AR0qixNg-dMJBsjhVo3UXIg7RixR66pxOiblU:IvFD52ZHDLGhomSjpP13fOvUZew=',
          },
        },
        {
          id: 4909977,
          field_id: 10785,
          option_id: null,
          value: 'logo.jpg',
          choice_id: null,
          value_id: 948500,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
          attachment: {
            id: 948500,
            name: 'logo.jpg',
            size: '33554',
            mime_type: 'image/jpeg',
            extension: 'image',
            extra_info: {},
            download_url:
              'http://gxattachment.skylarkly.com/1/create_responses/6-1610522321-3203f50552a473e93bb9f89531e755a1-Wed Jan 13 2021 15:18:38 GMT+0800 (中国标准时间)?attname=logo.jpg&e=1610527775&token=fy5AR0qixNg-dMJBsjhVo3UXIg7RixR66pxOiblU:bQRTL1ENdEjU-NT2pdt9rzVANcU=',
          },
        },
        {
          id: 4892902,
          field_id: 10724,
          option_id: 14545,
          value: '男、女、帅',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4892900,
          field_id: 10750,
          option_id: 14717,
          value: '男',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4891418,
          field_id: 10282,
          option_id: null,
          value: '男',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
        {
          id: 4889232,
          field_id: 10181,
          option_id: null,
          value: '测试测试',
          choice_id: null,
          value_id: null,
          latitude: null,
          longitude: null,
          group_id: null,
          detail_id: null,
        },
      ],
    }
  },

  created() {
    this.flow = {
      id: 805,
      title: '材料库测试流程',
      external_settings: {
        upload: { size: 0.1, count: 2, accept: 'image/*,.pdf,.xlsx' },
        form_id: 326,
        fields_mapping: {
          sex: 'sex',
          date: 'date',
          file: 'file',
          phone: 'phone',
          openId: 'openId',
          sexDown: 'sexDown',
          checkbox: 'checkbox',
          checkboxDown: 'checkboxDown',
          flow_id_card: 'cardid',
          flow_username: 'name',
        },
        disabled_fields: ['flow_username'],
      },
      identity_vertify_type: 'off',
      fields: [
        {
          id: 10181,
          title: '姓名',
          description: "测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试",
          type: 'Field::TextField',
          position: 0,
          validations: ['presence'],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'block',
            char_size_limit_settings: {},
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            enable_wechat_scan: false,
          },
          detail_id: null,
          identity_key: 'flow_usernam',
          data: {},
        },
        {
          id: 20181,
          title: '姓名（平铺）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::TextField',
          position: 0,
          validations: ['presence'],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            char_size_limit_settings: {},
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            enable_wechat_scan: false,
          },
          detail_id: null,
          identity_key: 'flow_username',
          data: {},
        },
        {
          id: 30181,
          title: '多行文本',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::TextArea',
          position: 0,
          validations: ['presence'],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'block',
            char_size_limit_settings: {},
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            enable_wechat_scan: false,
          },
          detail_id: null,
          identity_key: 'flow_usename',
          data: {},
        },
        {
          id: 40181,
          title: '多行文本（平铺）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::TextArea',
          position: 0,
          validations: ['presence'],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            char_size_limit_settings: {},
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            enable_wechat_scan: false,
          },
          detail_id: null,
          identity_key: 'flow_sername',
          data: {},
        },
        {
          id: 10282,
          title: '单选（平铺）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::RadioButton',
          position: 1,
          validations: [],
          other_option: '其他',
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'sex',
          data: {},
          options: [
            {
              id: 13787,
              value: '男',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 0,
            },
            {
              id: 13788,
              value: '女',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 1,
            },
          ],
        },
        {
          id: 10935,
          title: '单选（列表）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::RadioButton',
          position: 2,
          validations: [],
          other_option: '其他',
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'list',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: '2c32cab73a1d413e89e0f7718cd74e1d',
          data: {},
          options: [
            {
              id: 14969,
              value: '男',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 0,
            },
            {
              id: 14970,
              value: '女',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 1,
            },
          ],
        },
        {
          id: 10750,
          title: '单选（下拉）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::RadioButton',
          position: 3,
          validations: [],
          other_option: '其他',
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'select',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'sexDown',
          data: {},
          options: [
            {
              id: 14717,
              value: '男',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 0,
            },
            {
              id: 14718,
              value: '女',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 1,
            },
          ],
        },
        {
          id: 10785,
          title: '文件上传',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::File',
          position: 4,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'block',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'file',
          data: {},
        },
        {
          id: 10724,
          title: '多选（平铺）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::CheckBox',
          position: 5,
          validations: [],
          other_option: '其他',
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'checkbox',
          data: {},
          options: [
            {
              id: 14545,
              value: '男',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 0,
            },
            {
              id: 14546,
              value: '女',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 1,
            },
            {
              id: 14547,
              value: '帅',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 2,
            },
          ],
        },
        {
          id: 10936,
          title: '多选（列表）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::CheckBox',
          position: 6,
          validations: [],
          other_option: '其他',
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'list',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: '5d123d6e223942adb1a972c9e5fa1bd1',
          data: {},
          options: [
            {
              id: 14971,
              value: '男',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 0,
            },
            {
              id: 14972,
              value: '女',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 1,
            },
            {
              id: 14973,
              value: '帅',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 2,
            },
          ],
        },
        {
          id: 10754,
          title: '多选（下拉）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::CheckBox',
          position: 7,
          validations: ['presence'],
          other_option: '其他',
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'select',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'checkboxDown',
          data: {},
          options: [
            {
              id: 14719,
              value: '男',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 0,
            },
            {
              id: 14720,
              value: '女',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 1,
            },
            {
              id: 14721,
              value: '帅',
              settings: { limit_settings: { max: null, text: '超过限制' } },
              position: 2,
            },
          ],
        },
        {
          id: 10172,
          title: '手机号',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::Phone',
          position: 8,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'phone',
          data: {},
        },
        {
          id: 10937,
          title: '手机号（区块）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::Phone',
          position: 9,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'block',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: '367234dc8a69419bb13b4454eaceb2eb',
          data: {},
        },
        {
          id: 10171,
          title: '身份证号码',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::IDNumber',
          position: 10,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'block',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'flow_id_card',
          data: {},
        },
        {
          id: 10938,
          title: '身份证号码（平铺）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::IDNumber',
          position: 11,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: '34a6e97cfd894720b020abad6c21ca24',
          data: {},
        },
        {
          id: 10725,
          title: '日期（区块）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::DateTime',
          position: 12,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'block',
            input_type: 'date',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: 'date',
          data: {},
        },
        {
          id: 10939,
          title: '日期（平铺）',
          description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
          type: 'Field::DateTime',
          position: 13,
          validations: [],
          other_option: null,
          visibility: 'public_visibility',
          marked: false,
          settings: {
            layout: 'inline',
            input_type: 'date',
            other_option_settings: { limit: {} },
            length_limit: {},
            limit_settings: {},
            char_size_limit_settings: {},
          },
          detail_id: null,
          identity_key: '490b927c54a5430697f810f722d7534d',
          data: {},
        },
      ],
      vertices: [
        {
          id: 14031,
          name: '开始节点',
          type: 'YetAnotherWorkflow::Vertex::Initial',
          field_ids: [],
          operations: {
            route: { name: '选路', enabled: true },
            stash: { name: '保存', enabled: true },
            cancel: { name: '撤销', enabled: true },
            remind: { name: '催促', enabled: true },
            comment: { name: '处理意见', enabled: true },
            propose: { name: '发起', enabled: true },
            esignature: { name: '电子签字', enabled: false },
          },
          settings: {
            carbon_copy: { enable_manual: false },
            refuse_mode: 1,
            assign_manually: false,
            batch_processing: false,
            distributed_equally: false,
          },
          metadata: { position: { x: 400, y: 100 } },
          alias_name: null,
          fields: [
            {
              id: 10181,
              title: '姓名',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::TextField',
              position: 0,
              validations: ['presence'],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'block',
                char_size_limit_settings: {},
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                enable_wechat_scan: false,
              },
              detail_id: null,
              identity_key: 'flow_username',
              data: {},
            },
            {
              id: 10282,
              title: '单选（平铺）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::RadioButton',
              position: 1,
              validations: [],
              other_option: '其他',
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'inline',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'sex',
              data: {},
              options: [
                {
                  id: 13787,
                  value: '男',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 0,
                },
                {
                  id: 13788,
                  value: '女',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 1,
                },
              ],
            },
            {
              id: 10935,
              title: '单选（列表）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::RadioButton',
              position: 2,
              validations: [],
              other_option: '其他',
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'list',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: '2c32cab73a1d413e89e0f7718cd74e1d',
              data: {},
              options: [
                {
                  id: 14969,
                  value: '男',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 0,
                },
                {
                  id: 14970,
                  value: '女',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 1,
                },
              ],
            },
            {
              id: 10750,
              title: '单选（下拉）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::RadioButton',
              position: 3,
              validations: [],
              other_option: '其他',
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'select',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'sexDown',
              data: {},
              options: [
                {
                  id: 14717,
                  value: '男',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 0,
                },
                {
                  id: 14718,
                  value: '女',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 1,
                },
              ],
            },
            {
              id: 10785,
              title: '文件上传',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::File',
              position: 4,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'block',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'file',
              data: {},
            },
            {
              id: 10724,
              title: '多选（平铺）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::CheckBox',
              position: 5,
              validations: [],
              other_option: '其他',
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'inline',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'checkbox',
              data: {},
              options: [
                {
                  id: 14545,
                  value: '男',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 0,
                },
                {
                  id: 14546,
                  value: '女',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 1,
                },
                {
                  id: 14547,
                  value: '帅',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 2,
                },
              ],
            },
            {
              id: 10936,
              title: '多选（列表）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::CheckBox',
              position: 6,
              validations: [],
              other_option: '其他',
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'list',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: '5d123d6e223942adb1a972c9e5fa1bd1',
              data: {},
              options: [
                {
                  id: 14971,
                  value: '男',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 0,
                },
                {
                  id: 14972,
                  value: '女',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 1,
                },
                {
                  id: 14973,
                  value: '帅',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 2,
                },
              ],
            },
            {
              id: 10754,
              title: '多选（下拉）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::CheckBox',
              position: 7,
              validations: ['presence'],
              other_option: '其他',
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'select',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'checkboxDown',
              data: {},
              options: [
                {
                  id: 14719,
                  value: '男',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 0,
                },
                {
                  id: 14720,
                  value: '女',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 1,
                },
                {
                  id: 14721,
                  value: '帅',
                  settings: { limit_settings: { max: null, text: '超过限制' } },
                  position: 2,
                },
              ],
            },
            {
              id: 10172,
              title: '手机号',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::Phone',
              position: 8,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'inline',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'phone',
              data: {},
            },
            {
              id: 10937,
              title: '手机号（区块）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::Phone',
              position: 9,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'block',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: '367234dc8a69419bb13b4454eaceb2eb',
              data: {},
            },
            {
              id: 10171,
              title: '身份证号码',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::IDNumber',
              position: 10,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'block',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'flow_id_card',
              data: {},
            },
            {
              id: 10938,
              title: '身份证号码（平铺）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::IDNumber',
              position: 11,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'inline',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: '34a6e97cfd894720b020abad6c21ca24',
              data: {},
            },
            {
              id: 10725,
              title: '日期（区块）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::DateTime',
              position: 12,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'block',
                input_type: 'date',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: 'date',
              data: {},
            },
            {
              id: 10939,
              title: '日期（平铺）',
              description: '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试',
              type: 'Field::DateTime',
              position: 13,
              validations: [],
              other_option: null,
              visibility: 'public_visibility',
              marked: false,
              settings: {
                layout: 'inline',
                input_type: 'date',
                other_option_settings: { limit: {} },
                length_limit: {},
                limit_settings: {},
                char_size_limit_settings: {},
              },
              detail_id: null,
              identity_key: '490b927c54a5430697f810f722d7534d',
              data: {},
            },
          ],
        },
        {
          id: 14036,
          name: '流程节点',
          type: 'YetAnotherWorkflow::Vertex::Normal',
          field_ids: [],
          operations: {
            route: { name: '选路', enabled: true },
            refuse: { name: '回退', enabled: true },
            approve: { name: '通过', enabled: true },
            comment: { name: '处理意见', enabled: true },
            transfer: { name: '转交', enabled: true },
            esignature: { name: '电子签字', enabled: false },
          },
          settings: {
            carbon_copy: { enable_manual: false },
            refuse_mode: 1,
            assign_manually: false,
            batch_processing: false,
            duration_threshold: {
              value: null,
              enable_delay: false,
              business_time: { final: '17:00', initial: '09:00', workday: true },
              enable_manual: false,
              enable_business_time: false,
            },
            distributed_equally: false,
          },
          metadata: { position: { x: 417, y: 181.2734375 } },
          alias_name: '',
          fields: [],
        },
        {
          id: 14041,
          name: '流程节点',
          type: 'YetAnotherWorkflow::Vertex::Normal',
          field_ids: [],
          operations: {
            route: { name: '选路', enabled: true },
            refuse: { name: '回退', enabled: true },
            approve: { name: '通过', enabled: true },
            comment: { name: '处理意见', enabled: true },
            transfer: { name: '转交', enabled: true },
            esignature: { name: '电子签字', enabled: false },
          },
          settings: {
            carbon_copy: { enable_manual: false },
            refuse_mode: 1,
            assign_manually: false,
            batch_processing: false,
            duration_threshold: {
              value: null,
              enable_delay: false,
              business_time: { final: '17:00', initial: '09:00', workday: true },
              enable_manual: false,
              enable_business_time: false,
            },
            distributed_equally: false,
          },
          metadata: { position: { x: 284, y: 263.71875 } },
          alias_name: '',
          fields: [],
        },
        {
          id: 14040,
          name: '流程节点',
          type: 'YetAnotherWorkflow::Vertex::Normal',
          field_ids: [],
          operations: {
            route: { name: '选路', enabled: true },
            refuse: { name: '回退', enabled: true },
            approve: { name: '通过', enabled: true },
            comment: { name: '处理意见', enabled: true },
            transfer: { name: '转交', enabled: true },
            esignature: { name: '电子签字', enabled: false },
          },
          settings: {
            carbon_copy: { enable_manual: false },
            refuse_mode: 1,
            assign_manually: false,
            batch_processing: false,
            duration_threshold: {
              value: null,
              enable_delay: false,
              business_time: { final: '17:00', initial: '09:00', workday: true },
              enable_manual: false,
              enable_business_time: false,
            },
            distributed_equally: false,
          },
          metadata: { position: { x: 486, y: 265.71875 } },
          alias_name: '',
          fields: [],
        },
        {
          id: 14032,
          name: '结束节点',
          type: 'YetAnotherWorkflow::Vertex::Final',
          field_ids: [],
          operations: {},
          settings: {},
          metadata: { position: { x: 400, y: 400 } },
          alias_name: null,
          fields: [],
        },
      ],
      edges: [
        { id: 18411, from_vertex_id: 14031, to_vertex_id: 14036 },
        { id: 18420, from_vertex_id: 14036, to_vertex_id: 14041 },
        { id: 18419, from_vertex_id: 14036, to_vertex_id: 14040 },
        { id: 18422, from_vertex_id: 14040, to_vertex_id: 14032 },
        { id: 18421, from_vertex_id: 14041, to_vertex_id: 14032 },
      ],
    }
  },

  methods: {
    beforeUploadFunc() {
      this.fileParams = { size: 2, accept: 'image/*,.pdf', count: 2 }
    },
  },
}
</script>
